### ISSUE TITLE
Implement TTS into Blightmud

### ISSUE THREAD

**Issue by LiquidityC** [LiquidityC/Blightmud#110]
To make blightmud more available to blind people a suggestion has been brought up to implement text-to-speech into the application. Partly by me.

This will be quite experimental but could also be a very fun and interesting challenge. It could also be useful to most users if implemented correctly for audio notifications etc.

## Implementation steps

- [x] Add the crate [tts](https://crates.io/crates/tts)
- [x] On boot spawn a thread with a channel open for sending text to the thread.
- [x] Create a TTSEvent that can be sent to TTS thread, this should be used to control settings etc.
- [x] Introduce a commandline option to control if this thread is started or not `--tts` (default `false`)
- [x] ~~Update the `line.rs` object with a flag `tts`~~
- [x] ~~Update the `Line::tts` flag to default to true or false depending on the `default-tts` setting~~
- [x] Add the flags `tts_force`, `tts_gag` and `tts_interrupt` to `line.rs`
- [x] Introduce a setting `default-tts` in `settings.rs` (default `true`)
- [x] Create event handler that forwards `output` events to the `tts_thread`
- [x] Add lua script to allow setting of the `tts` value on line objects from lua. (look how `gag` works and also make `gag` set `tts = false`)
- [x] Add lua function `blight::tts(message)` that will speak whatever message you give it
- [x] Add a completely new documentation section for tts functionality

## Remaining thoughts and possible future modifications
- How do we deal with scrolling? Input from anyone experienced with screen readers would be nice here.
- What about helpfiles? Currently they dump a lot of text at once when you open them. Do we want the TTS to spam all that?
- Is a command that empties the TTS buffer needed? If the TTS is talking to much do you want to be able to shut it up with a quick command/keypress?
- Do we want to hide all the TTS stuff behind a feature and supply two releases? I don't want it to impact anyone currently using blightmud in a negative way. So if you're not interested in TTS it shouldn't make any noise (no pun intended).

## Important notes
- **All work should be done against the `tts_impl` branch**
- **All tts specific code should be placed in a new module named `tts` (eg. `src/tts/*.rs`)**

**Comment by LiquidityC** [comment]
Based on how the tts crate works I changed the specs around slightly.
This is my thinking.
- TTS should be as isolated from the core code as possible (this is generally just a good standard)
- If TTS is enabled everything is spoken except lines with the `tts_gag` flag set to true
- If TTS is disabled only lines with the flag `tts_force` should be spoken (This is something that I will use :smile: )
- The TTSEvents that you send to the tts_thread should be able to toggle speech rate and other "useful" options. All this should be controlled through lua.
- We'll introduce a new lua `UserData` called tts to control these settings and sending direct "speaks" to the tts thread.
- The commandline flag `--tts` should control if tts is enabled/disabled. Default (no flag) means disabled. Eg. It only speaks what you tell it to speak.
- We should probably hide this TTS stuff behind a feature. I don't want it to cause trouble if you're compiling Blightmud on a headless machine. But so far it seems to work fine on the CI builds so perhaps this isn't an issue at all.

**Comment by LiquidityC** [comment]
Ok, this is what we have now in the `tts_impl` branch.

TTS defaults to on for now. Everything is spoken out. Errors and info are modified slightly to be nicer when spoken instead of the TTS shouting a bunch of asterisks.
Lines that don't contain any alphanumeric characters won't be spoken.
When you send a command, the TTS interupts, speaks what was sent and continues with whatever appears after your input. Is this good behavior? What's preferred?
There isn't and key command to make the TTS stop talking. I will add that in coming commits.

I'm going to add some settings. What is preferred here? Pitch, speed, volume?

Anyone accustomed to using a screen reader. Please test and give me feedback.

**Comment by LiquidityC** [comment]
This issue is done. Testing is done using the `tts_impl` branch. Any bugs or feature requests should be posted as new issues.
